scp bash script updated

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,19 +1,24 @@
 #!/usr/bin/env bash
 
-# This script transfers a file from a client to a server using scp
-
-# Check if we have the correct number of parameters
-if [[ $# -lt 4 ]]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+# Check if all required arguments have been provided
+if [ "$#" -lt 4 ]; then
+		echo "Usage: transfer_file.sh <path_to_file> <ip_address> <username> <path_to_ssh_key>"
+			exit 1
 fi
 
-# Get the parameters
-path_to_file="$1"
-ip="$2"
-username="$3"
-path_to_ssh_key="$4"
+# Assign the arguments to more descriptive variables
+local_path="$1"
+remote_ip="$2"
+remote_user="$3"
+ssh_key="$4"
 
-# Use scp to transfer the file
-scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+# Copy the file to the remote server using SCP
+scp -i "$ssh_key" -o StrictHostKeyChecking=no "$local_path" "$remote_user@$remote_ip":~/.
+
+# Check if the file transfer was successful
+if [ $? -eq 0 ]; then
+		echo "File transfer successful!"
+	else
+			echo "File transfer failed."
+fi
 
